In [125]:
import pandas as pd

In [126]:
import numpy as numpy

In [127]:
data = pd.read_csv("training_features.csv")

In [128]:
data.head()

,filename,genre,chroma_stft,rmse,spectral_centroid,spectral_bandwidth,rolloff,zero_crossing_rate,mfcc1,mfcc2,...,mfcc11,mfcc12,mfcc13,mfcc14,mfcc15,mfcc16,mfcc17,mfcc18,mfcc19,mfcc20
0,prog01._The_Same_River.mp3chunk1,prog,0.460696,0.034861,2136.532187,2941.974882,3709.237815,12.91667,-353.523132,154.181503,...,0.984727,-2.941462,2.282566,-5.822038,-5.619420,6.779680,2.217392,8.294171,5.122895,1.124692
1,prog01._The_Same_River.mp3chunk2,prog,0.474003,0.167274,916.001243,1810.250714,1582.214091,12.91667,-249.223022,213.542236,...,0.873292,-2.131122,0.955438,0.933085,-1.544405,1.552725,0.132526,-3.517410,1.949664,-1.843542
2,prog01._The_Same_River.mp3chunk3,prog,0.512077,0.177684,1055.070126,1922.583818,1971.176575,12.91667,-221.212433,208.132156,...,1.280137,1.001755,4.477807,2.233161,0.902896,0.398619,1.775858,-2.207218,2.748353,-1.587731
3,prog01._The_Same_River.mp3chunk4,prog,0.495807,0.193546,1142.245871,2192.268118,2136.726165,12.91667,-204.271332,200.389572,...,3.437450,1.767640,3.681897,5.582968,2.794631,3.266841,2.787343,-1.845538,2.010118,0.229032
4,prog01._The_Same_River.mp3chunk5,prog,0.491598,0.243681,2075.977373,3333.274999,4610.220277,12.91667,-117.777710,159.725891,...,-2.786487,0.567188,-2.181447,6.493794,1.815525,4.490687,1.582551,-3.321782,-0.422923,-0.754964

In [129]:
data.isnull().sum()

filename              0
genre                 0
chroma_stft           0
rmse                  0
spectral_centroid     0
spectral_bandwidth    0
rolloff               0
zero_crossing_rate    0
mfcc1                 0
mfcc2                 0
mfcc3                 0
mfcc4                 0
mfcc5                 0
mfcc6                 0
mfcc7                 0
mfcc8                 0
mfcc9                 0
mfcc10                0
mfcc11                0
mfcc12                0
mfcc13                0
mfcc14                0
mfcc15                0
mfcc16                0
mfcc17                0
mfcc18                0
mfcc19                0
mfcc20                0
dtype: int64

In [130]:
data.dtypes

filename               object
genre                  object
chroma_stft           float64
rmse                  float64
spectral_centroid     float64
spectral_bandwidth    float64
rolloff               float64
zero_crossing_rate    float64
mfcc1                 float64
mfcc2                 float64
mfcc3                 float64
mfcc4                 float64
mfcc5                 float64
mfcc6                 float64
mfcc7                 float64
mfcc8                 float64
mfcc9                 float64
mfcc10                float64
mfcc11                float64
mfcc12                float64
mfcc13                float64
mfcc14                float64
mfcc15                float64
mfcc16                float64
mfcc17                float64
mfcc18                float64
mfcc19                float64
mfcc20                float64
dtype: object

In [131]:
from sklearn.preprocessing import StandardScaler

In [132]:
transform = StandardScaler()

In [133]:
data_toscale = data.drop(columns=['filename', 'genre'])

In [134]:
scale_data = transform.fit_transform(data_toscale)

In [135]:
scale_data

array([[ 0.22261495, -1.44136539, -0.45584836, ...,  2.22238377,
         1.64231586,  0.70375674],
       [ 0.37276655,  0.17911666, -1.96311686, ..., -0.82539947,
         0.82154573, -0.11228119],
       [ 0.80237094,  0.30650946, -1.79137673, ..., -0.4873263 ,
         1.02813018, -0.04195259],
       ...,
       [-0.53295139,  0.44464606,  1.26658009, ..., -2.25029011,
         0.99067956, -2.56186689],
       [ 2.34496033, -0.28860198,  0.78046807, ..., -0.89297055,
         2.23761738, -1.76858448],
       [ 1.69607496, -0.02132173,  1.1720755 , ..., -1.35704432,
         2.13282774, -1.70779837]])

In [136]:
scaled_data = pd.DataFrame(scale_data)

In [137]:
scaled_data

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,0.222615,-1.441365,-0.455848,-0.048527,-0.763244,-0.765009,-1.474478,0.117347,0.568163,-2.160644,...,0.577112,-0.971904,0.819173,-1.377185,-1.006570,1.777281,1.029158,2.222384,1.642316,0.703757
1,0.372767,0.179117,-1.963117,-1.576875,-1.900415,-0.765009,-0.593370,2.126592,1.058510,-0.579375,...,0.556836,-0.824454,0.533622,-0.009237,-0.048382,0.568723,0.512256,-0.825399,0.821546,-0.112281
2,0.802371,0.306509,-1.791377,-1.425174,-1.692464,-0.765009,-0.356742,1.943471,0.700032,-0.411732,...,0.630862,-0.254396,1.291511,0.254035,0.527070,0.301875,0.919688,-0.487326,1.028130,-0.041953
3,0.618789,0.500634,-1.683721,-1.060976,-1.603956,-0.765009,-0.213627,1.681400,1.242295,-0.070646,...,1.023385,-0.115036,1.120259,0.932388,0.971887,0.965055,1.170466,-0.394001,0.837182,0.457519
4,0.571294,1.114180,-0.530629,0.479909,-0.281551,-0.765009,0.517055,0.305014,1.319442,0.494219,...,-0.109060,-0.333470,-0.141325,1.116835,0.741663,1.248028,0.871761,-0.774921,0.207866,0.186995
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5108,1.185642,-0.018940,0.488469,0.564175,0.637933,0.586524,0.325960,-0.490808,-0.202791,1.253581,...,-0.064657,0.132197,0.736837,0.143289,-0.285050,-1.099513,0.290929,-2.107500,1.209151,-1.836090
5109,0.358928,-0.001718,0.138378,0.485190,0.297127,0.586524,0.097832,-0.414678,0.240278,0.933974,...,1.502800,-0.250037,0.050262,1.261335,-0.987152,-2.410887,-0.068284,-2.258620,-0.120199,-1.427614
5110,-0.532951,0.444646,1.266580,0.973797,1.293083,0.586524,0.800587,-0.901912,-0.792942,1.349385,...,-0.056940,1.030014,0.390727,0.435921,0.087249,-1.812217,-0.151538,-2.250290,0.990680,-2.561867
5111,2.344960,-0.288602,0.780468,0.917911,1.006536,0.586524,0.143507,-0.875134,0.354262,1.362273,...,-0.743813,0.106831,0.371328,0.216306,0.688583,-0.456031,1.098086,-0.892971,2.237617,-1.768584
5112,1.696075,-0.021322,1.172075,0.975041,1.237176,0.586524,0.528897,-0.982509,-0.358638,1.582231,...,-0.821256,0.119100,0.004823,-0.022715,0.331195,-0.506253,0.987455,-1.357044,2.132828,-1.707798

In [138]:
scaled_dataset = pd.DataFrame(scale_data, columns=data_toscale.columns)

In [139]:
scaled_dataset.head()

,chroma_stft,rmse,spectral_centroid,spectral_bandwidth,rolloff,zero_crossing_rate,mfcc1,mfcc2,mfcc3,mfcc4,...,mfcc11,mfcc12,mfcc13,mfcc14,mfcc15,mfcc16,mfcc17,mfcc18,mfcc19,mfcc20
0,0.222615,-1.441365,-0.455848,-0.048527,-0.763244,-0.765009,-1.474478,0.117347,0.568163,-2.160644,...,0.577112,-0.971904,0.819173,-1.377185,-1.006570,1.777281,1.029158,2.222384,1.642316,0.703757
1,0.372767,0.179117,-1.963117,-1.576875,-1.900415,-0.765009,-0.593370,2.126592,1.058510,-0.579375,...,0.556836,-0.824454,0.533622,-0.009237,-0.048382,0.568723,0.512256,-0.825399,0.821546,-0.112281
2,0.802371,0.306509,-1.791377,-1.425174,-1.692464,-0.765009,-0.356742,1.943471,0.700032,-0.411732,...,0.630862,-0.254396,1.291511,0.254035,0.527070,0.301875,0.919688,-0.487326,1.028130,-0.041953
3,0.618789,0.500634,-1.683721,-1.060976,-1.603956,-0.765009,-0.213627,1.681400,1.242295,-0.070646,...,1.023385,-0.115036,1.120259,0.932388,0.971887,0.965055,1.170466,-0.394001,0.837182,0.457519
4,0.571294,1.114180,-0.530629,0.479909,-0.281551,-0.765009,0.517055,0.305014,1.319442,0.494219,...,-0.109060,-0.333470,-0.141325,1.116835,0.741663,1.248028,0.871761,-0.774921,0.207866,0.186995

In [140]:
scaled_dataset['filename'] = data['filename']
scaled_dataset['genre'] = data['genre']

In [141]:
scaled_dataset.head()

,chroma_stft,rmse,spectral_centroid,spectral_bandwidth,rolloff,zero_crossing_rate,mfcc1,mfcc2,mfcc3,mfcc4,...,mfcc13,mfcc14,mfcc15,mfcc16,mfcc17,mfcc18,mfcc19,mfcc20,filename,genre
0,0.222615,-1.441365,-0.455848,-0.048527,-0.763244,-0.765009,-1.474478,0.117347,0.568163,-2.160644,...,0.819173,-1.377185,-1.006570,1.777281,1.029158,2.222384,1.642316,0.703757,prog01._The_Same_River.mp3chunk1,prog
1,0.372767,0.179117,-1.963117,-1.576875,-1.900415,-0.765009,-0.593370,2.126592,1.058510,-0.579375,...,0.533622,-0.009237,-0.048382,0.568723,0.512256,-0.825399,0.821546,-0.112281,prog01._The_Same_River.mp3chunk2,prog
2,0.802371,0.306509,-1.791377,-1.425174,-1.692464,-0.765009,-0.356742,1.943471,0.700032,-0.411732,...,1.291511,0.254035,0.527070,0.301875,0.919688,-0.487326,1.028130,-0.041953,prog01._The_Same_River.mp3chunk3,prog
3,0.618789,0.500634,-1.683721,-1.060976,-1.603956,-0.765009,-0.213627,1.681400,1.242295,-0.070646,...,1.120259,0.932388,0.971887,0.965055,1.170466,-0.394001,0.837182,0.457519,prog01._The_Same_River.mp3chunk4,prog
4,0.571294,1.114180,-0.530629,0.479909,-0.281551,-0.765009,0.517055,0.305014,1.319442,0.494219,...,-0.141325,1.116835,0.741663,1.248028,0.871761,-0.774921,0.207866,0.186995,prog01._The_Same_River.mp3chunk5,prog

In [142]:
from sklearn.linear_model import LogisticRegression

In [143]:
model = LogisticRegression()

In [144]:
def extract_song_name(filename):
    parts = filename.split('._')
    song_name_with_extension = parts[1].split('.')[0] if len(parts) > 1 else 'Unknown'
    return song_name_with_extension.rsplit('.', 1)[0]

In [145]:
df = pd.DataFrame(scaled_dataset)

In [146]:
df['Song'] = df['filename'].apply(extract_song_name)

In [147]:
# //print all unique songs
df['Song'].unique()

array(['The_Same_River', 'In_the_Flesh',
       'Anekdoten_-_Our_Days_Are_Numbered', 'Unknown',
       'The_Road_Of_Bones', 'Part_V', 'Hallogallo', 'Folklore',
       'Bo_Hansson_-_Rohans_Horn_-_Slaget_vid_Pelennors_slatter',
       'Second_Life_Syndrome', 'Omen', 'Guardian',
       'When_the_Water_Breaks', 'Milliontown', 'Hazard_Profile_Part_One',
       'The_Solid_Time_of_Change_II', 'Vert', 'The_Light', 'Bleed_(live)',
       'The_Czar_I', 'Mister_Broken_Wings',
       'Violin_Concerto_in_E_minor_op', 'B',
       'Air_Supply_-_All_Out_Of_Love', 'In_A_Gadda_Da_Vida',
       'Planet_Earth', 'Frank_Sinatra_-_The_Girl_From_Ipanema',
       'Painkiller', 'Billy_Ray_Cyrus)',
       'My_Beautiful_Dark_Twisted_Fantasy_-_POWER', 'Rag_Doll',
       'Michael_Sembello_-_Maniac', 'Ascension_(feat', '(Feat',
       'This_Time', '2_-_1', 'Top_Of_The_World',
       'The_Cars_-_Bye_Bye_Love', 'Chip_Tha_Ripper)', 'Black_Hole_Sun',
       'The_Weeknd,_Swae_Lee', 'Ed_Sheeran_&_Future)', 'Ten-Day_Interval',
       'Blue_Jeans', 'Nice_Guy', 'Happier_Than_Ever', 'Tel_Aviv', '1)',
       'Goode'], dtype=object)

In [148]:
from sklearn.model_selection import GroupShuffleSplit

gss = GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
train_idx, test_idx = next(gss.split(df, groups=df['Song']))

# Create train and test DataFrames
train_df = df.iloc[train_idx]
test_df = df.iloc[test_idx]

# Print results
print("Train DataFrame:")
print(train_df)
print("\nTest DataFrame:")
print(test_df)

Train DataFrame:
      chroma_stft      rmse  spectral_centroid  spectral_bandwidth   rolloff  \
0        0.222615 -1.441365          -0.455848           -0.048527 -0.763244
1        0.372767  0.179117          -1.963117           -1.576875 -1.900415
2        0.802371  0.306509          -1.791377           -1.425174 -1.692464
3        0.618789  0.500634          -1.683721           -1.060976 -1.603956
4        0.571294  1.114180          -0.530629            0.479909 -0.281551
...           ...       ...                ...                 ...       ...
4832     1.031740  1.946736           0.121573            0.544694  0.300970
4886    -0.814633  0.173076           0.105645            0.054046 -0.126585
4887    -0.648583  0.213270           0.216607            0.322978  0.065566
4888    -0.747192  0.246450           0.027847           -0.048090 -0.316403
4889    -0.555765  0.457003           0.432998            0.560782  0.314061

      zero_crossing_rate     mfcc1     mfcc2     mfcc3     mfcc4  ...  \
0              -0.765009 -1.474478  0.117347  0.568163 -2.160644  ...
1              -0.765009 -0.593370  2.126592  1.058510 -0.579375  ...
2              -0.765009 -0.356742  1.943471  0.700032 -0.411732  ...
3              -0.765009 -0.213627  1.681400  1.242295 -0.070646  ...
4              -0.765009  0.517055  0.305014  1.319442  0.494219  ...
...                  ...       ...       ...       ...       ...  ...
4832            0.435469  0.684521 -0.545199  0.023188  0.373411  ...
4886            2.183208  0.488339 -0.020905 -0.688273 -1.223669  ...
4887            2.183208  0.633496 -0.088255 -0.413342 -0.843019  ...
4888            2.183208  0.635915  0.219603 -0.955887 -1.332232  ...
4889            2.183208  0.802283 -0.174866 -0.419279 -0.705844  ...

        mfcc14    mfcc15    mfcc16    mfcc17    mfcc18    mfcc19    mfcc20  \
0    -1.377185 -1.006570  1.777281  1.029158  2.222384  1.642316  0.703757
1    -0.009237 -0.048382  0.568723  0.512256 -0.825399  0.821546 -0.112281
2     0.254035  0.527070  0.301875  0.919688 -0.487326  1.028130 -0.041953
3     0.932388  0.971887  0.965055  1.170466 -0.394001  0.837182  0.457519
4     1.116835  0.741663  1.248028  0.871761 -0.774921  0.207866  0.186995
...        ...       ...       ...       ...       ...       ...       ...
4832  1.064083  0.711515  1.177275  1.335220  1.296928  0.144324  0.233103
4886  0.874730 -0.384397  1.096307 -0.115743 -0.065052  0.088759  0.528898
4887  0.810445 -0.050547  1.096949  0.384943 -0.335861  0.404607  0.167441
4888  0.759065 -0.428629  0.543073  0.236707  0.689036  0.456650  1.170450
4889  1.104528 -0.354876  1.164170 -0.335917  0.101510  0.045812  0.705833

                                        filename     genre            Song
0               prog01._The_Same_River.mp3chunk1      prog  The_Same_River
1               prog01._The_Same_River.mp3chunk2      prog  The_Same_River
2               prog01._The_Same_River.mp3chunk3      prog  The_Same_River
3               prog01._The_Same_River.mp3chunk4      prog  The_Same_River
4               prog01._The_Same_River.mp3chunk5      prog  The_Same_River
...                                          ...       ...             ...
4832  nonprog01_Play_Your_Part_(Pt._1).mp3chunk7  non_prog              1)
4886         nonprog07_Johnny_B._Goode.mp3chunk1  non_prog           Goode
4887         nonprog07_Johnny_B._Goode.mp3chunk2  non_prog           Goode
4888         nonprog07_Johnny_B._Goode.mp3chunk3  non_prog           Goode
4889         nonprog07_Johnny_B._Goode.mp3chunk4  non_prog           Goode

[482 rows x 29 columns]

Test DataFrame:
      chroma_stft      rmse  spectral_centroid  spectral_bandwidth   rolloff  \
45      -1.614458 -1.472406          -1.577174           -1.662285 -1.639775
46      -1.385687 -1.315350          -1.660280           -1.753385 -1.765692
47      -1.631662 -1.566462          -1.272654           -1.255144 -1.516936
48      -0.601355 -1.616671          -0.594445           -0.824751 -0.958086
49      -0.004607 -1.442703          -0.101218           -0.038003 -0.173407
...           ...       ...                ...                 ...       ...
5108     1.185642 -0.018940           0.488469            0.564175  0.637933
5109     0.358928 -0.001718           0.138378            0.485190  0.297127
5110    -0.532951  0.444646           1.266580            0.973797  1.293083
5111     2.344960 -0.288602           0.780468            0.917911  1.006536
5112     1.696075 -0.021322           1.172075            0.975041  1.237176

      zero_crossing_rate     mfcc1     mfcc2     mfcc3     mfcc4  ...  \
45             -0.530028 -1.659406  1.284523  0.767863 -2.704260  ...
46             -0.530028 -1.425404  1.691214  0.898045 -2.866900  ...
47             -0.530028 -1.752651  0.965253  0.787069 -2.401937  ...
48             -0.530028 -1.229354  1.149612 -1.170931 -1.118769  ...
49             -0.530028 -0.667877  0.124938 -0.270638 -0.715656  ...
...                  ...       ...       ...       ...       ...  ...
5108            0.586524  0.325960 -0.490808 -0.202791  1.253581  ...
5109            0.586524  0.097832 -0.414678  0.240278  0.933974  ...
5110            0.586524  0.800587 -0.901912 -0.792942  1.349385  ...
5111            0.586524  0.143507 -0.875134  0.354262  1.362273  ...
5112            0.586524  0.528897 -0.982509 -0.358638  1.582231  ...

        mfcc14    mfcc15    mfcc16    mfcc17    mfcc18    mfcc19    mfcc20  \
45   -1.302641 -1.379834 -1.270841  0.208935  0.889183  1.180971  1.415519
46   -1.150564 -0.451682 -0.608636 -0.022196 -0.036806  0.081828  0.461592
47   -1.217663 -0.907290 -1.330351 -0.497429  0.193758  0.945660  1.143700
48   -1.391863  0.597872 -0.723520  0.362736 -1.551578  0.487795 -0.514401
49   -1.388145  0.916671  0.169647  1.004699 -0.983885  0.300429 -0.240526
...        ...       ...       ...       ...       ...       ...       ...
5108  0.143289 -0.285050 -1.099513  0.290929 -2.107500  1.209151 -1.836090
5109  1.261335 -0.987152 -2.410887 -0.068284 -2.258620 -0.120199 -1.427614
5110  0.435921  0.087249 -1.812217 -0.151538 -2.250290  0.990680 -2.561867
5111  0.216306  0.688583 -0.456031  1.098086 -0.892971  2.237617 -1.768584
5112 -0.022715  0.331195 -0.506253  0.987455 -1.357044  2.132828 -1.707798

                                        filename     genre     Song
45            prog07_-_Fool's_Overture.mp3chunk1      prog  Unknown
46            prog07_-_Fool's_Overture.mp3chunk2      prog  Unknown
47            prog07_-_Fool's_Overture.mp3chunk3      prog  Unknown
48            prog07_-_Fool's_Overture.mp3chunk4      prog  Unknown
49            prog07_-_Fool's_Overture.mp3chunk5      prog  Unknown
...                                          ...       ...      ...
5108  nonprogCranberries_-_04_-_Zombie.mp3chunk4  non_prog  Unknown
5109  nonprogCranberries_-_04_-_Zombie.mp3chunk5  non_prog  Unknown
5110  nonprogCranberries_-_04_-_Zombie.mp3chunk6  non_prog  Unknown
5111  nonprogCranberries_-_04_-_Zombie.mp3chunk7  non_prog  Unknown
5112  nonprogCranberries_-_04_-_Zombie.mp3chunk8  non_prog  Unknown

[4631 rows x 29 columns]

In [149]:
train_df.dtypes

chroma_stft           float64
rmse                  float64
spectral_centroid     float64
spectral_bandwidth    float64
rolloff               float64
zero_crossing_rate    float64
mfcc1                 float64
mfcc2                 float64
mfcc3                 float64
mfcc4                 float64
mfcc5                 float64
mfcc6                 float64
mfcc7                 float64
mfcc8                 float64
mfcc9                 float64
mfcc10                float64
mfcc11                float64
mfcc12                float64
mfcc13                float64
mfcc14                float64
mfcc15                float64
mfcc16                float64
mfcc17                float64
mfcc18                float64
mfcc19                float64
mfcc20                float64
filename               object
genre                  object
Song                   object
dtype: object

In [150]:
model.fit(train_df.drop(columns = ['genre', 'filename', 'Song']), train_df['genre'])

LogisticRegression()

In [151]:
train_df['pred'] = model.predict(train_df.drop(columns = ['genre', 'filename', 'Song']))
test_df['pred'] = model.predict(test_df.drop(columns = ['genre', 'filename', 'Song']))

/var/folders/m0/0p062cxn2rvbyqh1m3h8cb4c0000gn/T/ipykernel_34475/230968207.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df['pred'] = model.predict(train_df.drop(columns = ['genre', 'filename', 'Song']))
/var/folders/m0/0p062cxn2rvbyqh1m3h8cb4c0000gn/T/ipykernel_34475/230968207.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_df['pred'] = model.predict(test_df.drop(columns = ['genre', 'filename', 'Song']))

In [152]:
from sklearn.metrics import accuracy_score
accuracy_train = accuracy_score(train_df['genre'], train_df['pred'])
accuracy_test = accuracy_score(test_df['genre'], test_df['pred'])
print(accuracy_train)
print(accuracy_test)

0.9356846473029046
0.7423882530770892

In [153]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
train_df['genre'] = label_encoder.fit_transform(train_df['genre'])
test_df['genre'] = label_encoder.transform(test_df['genre'])

/var/folders/m0/0p062cxn2rvbyqh1m3h8cb4c0000gn/T/ipykernel_34475/607645348.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df['genre'] = label_encoder.fit_transform(train_df['genre'])
/var/folders/m0/0p062cxn2rvbyqh1m3h8cb4c0000gn/T/ipykernel_34475/607645348.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_df['genre'] = label_encoder.transform(test_df['genre'])

In [154]:
X_train = train_df.drop(columns=['genre', 'filename', 'Song', 'pred'])
y_train = train_df['genre']
X_test = test_df.drop(columns=['genre', 'filename', 'Song', 'pred'])
y_test = test_df['genre']

In [155]:
import tensorflow as tf
from tensorflow.keras import regularizers
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping

model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(128, activation='relu', input_shape=(X_train.shape[1],)),  # Correct input shape
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

model.summary()

/Users/harlow/.local/share/virtualenvs/Progect-tV540T77/lib/python3.11/site-packages/keras/src/layers/core/dense.py:88: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_8 (Dense)                 │ (None, 128)            │         3,456 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_6 (Dropout)             │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_7 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_8 (Dropout)             │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 13,825 (54.00 KB)

 Trainable params: 13,825 (54.00 KB)

 Non-trainable params: 0 (0.00 B)

In [156]:
history = model.fit(X_train, y_train, epochs=50, verbose=1)

Epoch 1/50

16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 663us/step - accuracy: 0.5431 - loss: 0.7040
Epoch 2/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 616us/step - accuracy: 0.6573 - loss: 0.6552
Epoch 3/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 594us/step - accuracy: 0.6543 - loss: 0.6401
Epoch 4/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 708us/step - accuracy: 0.6850 - loss: 0.6015
Epoch 5/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 674us/step - accuracy: 0.6960 - loss: 0.5918
Epoch 6/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 590us/step - accuracy: 0.6927 - loss: 0.5837
Epoch 7/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 599us/step - accuracy: 0.7122 - loss: 0.5414
Epoch 8/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 622us/step - accuracy: 0.7443 - loss: 0.5561
Epoch 9/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 530us/step - accuracy: 0.7750 - loss: 0.4713
Epoch 10/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 566us/step - accuracy: 0.7980 - loss: 0.4558
Epoch 11/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 593us/step - accuracy: 0.7873 - loss: 0.4673
Epoch 12/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 584us/step - accuracy: 0.7876 - loss: 0.4469
Epoch 13/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 522us/step - accuracy: 0.8381 - loss: 0.3841
Epoch 14/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 525us/step - accuracy: 0.8412 - loss: 0.3599
Epoch 15/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 564us/step - accuracy: 0.8345 - loss: 0.3680
Epoch 16/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 603us/step - accuracy: 0.8530 - loss: 0.3435
Epoch 17/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 596us/step - accuracy: 0.8784 - loss: 0.2726
Epoch 18/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 535us/step - accuracy: 0.8973 - loss: 0.2825
Epoch 19/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 537us/step - accuracy: 0.8987 - loss: 0.2582
Epoch 20/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 560us/step - accuracy: 0.9103 - loss: 0.2542
Epoch 21/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 613us/step - accuracy: 0.8600 - loss: 0.2759
Epoch 22/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 563us/step - accuracy: 0.9211 - loss: 0.2342
Epoch 23/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 577us/step - accuracy: 0.9158 - loss: 0.2058
Epoch 24/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 587us/step - accuracy: 0.9325 - loss: 0.2009
Epoch 25/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 578us/step - accuracy: 0.8976 - loss: 0.2623
Epoch 26/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 538us/step - accuracy: 0.9578 - loss: 0.1721
Epoch 27/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 535us/step - accuracy: 0.9472 - loss: 0.1834
Epoch 28/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 556us/step - accuracy: 0.9185 - loss: 0.2005
Epoch 29/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 567us/step - accuracy: 0.9299 - loss: 0.1859
Epoch 30/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 555us/step - accuracy: 0.9539 - loss: 0.1366
Epoch 31/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 539us/step - accuracy: 0.9624 - loss: 0.1253
Epoch 32/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 569us/step - accuracy: 0.9281 - loss: 0.1582
Epoch 33/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 550us/step - accuracy: 0.9609 - loss: 0.1394
Epoch 34/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 700us/step - accuracy: 0.9629 - loss: 0.1284
Epoch 35/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 544us/step - accuracy: 0.9379 - loss: 0.1790
Epoch 36/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 591us/step - accuracy: 0.9734 - loss: 0.0899
Epoch 37/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 590us/step - accuracy: 0.9500 - loss: 0.1328
Epoch 38/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 536us/step - accuracy: 0.9491 - loss: 0.1488
Epoch 39/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 534us/step - accuracy: 0.9600 - loss: 0.1110
Epoch 40/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 553us/step - accuracy: 0.9659 - loss: 0.0927
Epoch 41/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 568us/step - accuracy: 0.9654 - loss: 0.1095
Epoch 42/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 569us/step - accuracy: 0.9630 - loss: 0.0939
Epoch 43/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 557us/step - accuracy: 0.9695 - loss: 0.1139
Epoch 44/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 617us/step - accuracy: 0.9556 - loss: 0.1222
Epoch 45/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 663us/step - accuracy: 0.9441 - loss: 0.1046
Epoch 46/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 615us/step - accuracy: 0.9783 - loss: 0.0961
Epoch 47/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 541us/step - accuracy: 0.9630 - loss: 0.1001
Epoch 48/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 586us/step - accuracy: 0.9601 - loss: 0.0984
Epoch 49/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 564us/step - accuracy: 0.9681 - loss: 0.0891
Epoch 50/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 556us/step - accuracy: 0.9694 - loss: 0.1065

In [157]:
test_loss, test_acc = model.evaluate(X_test, y_test, verbose=2)
print(f"Test Accuracy: {test_acc*100:.2f}%")

145/145 - 0s - 630us/step - accuracy: 0.7357 - loss: 1.4347
Test Accuracy: 73.57%