In [36]:
import pandas as pd

In [37]:
import numpy as numpy

In [38]:
data = pd.read_csv("training_features.csv")

In [39]:
data.head()

,filename,genre,chroma_stft,rmse,spectral_centroid,spectral_bandwidth,rolloff,zero_crossing_rate,mfcc1,mfcc2,...,mfcc11,mfcc12,mfcc13,mfcc14,mfcc15,mfcc16,mfcc17,mfcc18,mfcc19,mfcc20
0,prog01._The_Same_River.mp3chunk1,prog,0.412844,0.012020,2584.011759,3251.498483,4123.208710,12.91667,-412.344940,146.783371,...,3.093940,-3.107463,-0.864751,-9.901691,-4.813201,9.781146,2.514050,13.855376,6.156593,0.244649
1,prog01._The_Same_River.mp3chunk2,prog,0.447328,0.016777,2778.323385,3335.831973,4928.705386,12.91667,-366.398132,147.573807,...,4.782514,-10.306239,4.434219,-9.987293,-10.205784,4.983788,5.941105,7.832722,5.377849,-0.237876
2,prog01._The_Same_River.mp3chunk3,prog,0.549248,0.028440,1705.126704,2743.022655,3058.189474,12.91667,-377.122742,179.416946,...,8.050533,0.473583,6.908920,-3.858997,-4.700322,7.191614,-0.727203,8.219358,2.909396,-1.164925
3,prog01._The_Same_River.mp3chunk4,prog,0.473921,0.119102,1250.770798,2475.443205,2164.361700,12.91667,-255.759720,190.485046,...,-6.657756,-2.899806,0.128559,2.275627,-1.842629,4.593843,-0.973136,0.970178,6.900328,1.554077
4,prog01._The_Same_River.mp3chunk5,prog,0.446520,0.128075,896.740878,1874.693237,1518.340625,12.91667,-266.469116,216.051956,...,1.621624,-1.607628,2.394714,-0.092923,-0.695996,1.569792,-0.563106,-1.314994,4.349601,-0.911113

In [40]:
data.shape

(19605, 28)

In [41]:
data.isnull().sum()

filename              0
genre                 0
chroma_stft           0
rmse                  0
spectral_centroid     0
spectral_bandwidth    0
rolloff               0
zero_crossing_rate    0
mfcc1                 0
mfcc2                 0
mfcc3                 0
mfcc4                 0
mfcc5                 0
mfcc6                 0
mfcc7                 0
mfcc8                 0
mfcc9                 0
mfcc10                0
mfcc11                0
mfcc12                0
mfcc13                0
mfcc14                0
mfcc15                0
mfcc16                0
mfcc17                0
mfcc18                0
mfcc19                0
mfcc20                0
dtype: int64

In [42]:
data.dtypes

filename               object
genre                  object
chroma_stft           float64
rmse                  float64
spectral_centroid     float64
spectral_bandwidth    float64
rolloff               float64
zero_crossing_rate    float64
mfcc1                 float64
mfcc2                 float64
mfcc3                 float64
mfcc4                 float64
mfcc5                 float64
mfcc6                 float64
mfcc7                 float64
mfcc8                 float64
mfcc9                 float64
mfcc10                float64
mfcc11                float64
mfcc12                float64
mfcc13                float64
mfcc14                float64
mfcc15                float64
mfcc16                float64
mfcc17                float64
mfcc18                float64
mfcc19                float64
mfcc20                float64
dtype: object

In [43]:
from sklearn.preprocessing import StandardScaler

In [44]:
transform = StandardScaler()

In [45]:
data_toscale = data.drop(columns=['filename', 'genre'])

In [46]:
scale_data = transform.fit_transform(data_toscale)

In [47]:
scale_data

array([[-0.28662207, -1.61800768,  0.08547032, ...,  3.10157211,
         1.64215915,  0.38392298],
       [ 0.06201771, -1.56291426,  0.30523573, ...,  1.77905433,
         1.46958844,  0.27198762],
       [ 1.09247607, -1.42783907, -0.90854397, ...,  1.86395599,
         0.92257579,  0.05693261],
       ...,
       [ 1.560009  ,  0.12485493,  1.4920333 , ..., -1.02639856,
         2.13097864, -1.49616076],
       [ 1.35627776,  0.05186926,  1.17632621, ..., -1.076291  ,
         1.94070224, -1.31518212],
       [ 2.22615747, -0.54739615, -0.51977626, ..., -1.20626137,
         0.67899649, -1.32462926]])

In [48]:
scaled_data = pd.DataFrame(scale_data)

In [49]:
scaled_data

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,-0.286622,-1.618008,0.085470,0.342002,-0.499799,-0.776378,-1.749935,-0.187796,0.018807,-3.186727,...,0.886732,-0.921342,0.160322,-1.950076,-0.675093,2.095811,0.960045,3.101572,1.642159,0.383923
1,0.062018,-1.562914,0.305236,0.447540,-0.103498,-0.776378,-1.398961,-0.164109,-0.484784,-1.706009,...,1.153778,-2.071925,1.134710,-1.965194,-1.756498,1.144817,1.689571,1.779054,1.469588,0.271988
2,1.092476,-1.427839,-0.908544,-0.294322,-1.023783,-0.776378,-1.480883,0.790129,0.918671,-1.938466,...,1.670612,-0.348982,1.589764,-0.882939,-0.652456,1.582481,0.270070,1.863956,0.922576,0.056933
3,0.330889,-0.377849,-1.422418,-0.629180,-1.463543,-0.776378,-0.553826,1.121805,1.547780,-0.421892,...,-0.655488,-0.888152,0.342974,0.200433,-0.079387,1.067518,0.217717,0.272105,1.806972,0.687681
4,0.053858,-0.273925,-1.822824,-1.380979,-1.781383,-0.776378,-0.635632,1.887964,1.170838,-0.691961,...,0.653887,-0.681623,0.759681,-0.217852,0.150554,0.468052,0.305002,-0.229697,1.241727,0.115812
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19600,1.535647,-0.110191,1.296453,1.217391,1.530622,0.556312,0.526955,-0.962165,-0.226000,1.262120,...,-1.242372,-0.342649,-0.224053,0.096379,0.464166,-0.442927,1.204498,-0.968635,2.261563,-1.818282
19601,1.142626,0.080297,1.500796,1.195728,1.576968,0.556312,0.759706,-1.007968,-0.636482,1.312545,...,-1.128415,0.078093,0.040882,0.303402,0.548422,-0.046948,1.440025,-1.336964,2.247471,-1.291483
19602,1.560009,0.124855,1.492033,1.090082,1.487372,0.556312,0.810443,-1.019270,-0.704840,1.452837,...,-1.015265,0.153027,-0.068648,0.029712,0.347920,-0.389182,1.233379,-1.026399,2.130979,-1.496161
19603,1.356278,0.051869,1.176326,0.777677,1.146267,0.556312,0.675565,-0.881866,-0.681228,1.692391,...,-0.828254,-0.022899,-0.158120,-0.354271,0.136650,-0.732802,0.569400,-1.076291,1.940702,-1.315182
19604,2.226157,-0.547396,-0.519776,0.406176,-0.160144,0.556312,-0.769076,-0.860017,1.979349,1.056549,...,1.075462,0.234964,0.536049,-0.203521,0.109310,-0.976462,-0.269073,-1.206261,0.678996,-1.324629

In [50]:
scaled_dataset = pd.DataFrame(scale_data, columns=data_toscale.columns)

In [51]:
scaled_dataset.head()

,chroma_stft,rmse,spectral_centroid,spectral_bandwidth,rolloff,zero_crossing_rate,mfcc1,mfcc2,mfcc3,mfcc4,...,mfcc11,mfcc12,mfcc13,mfcc14,mfcc15,mfcc16,mfcc17,mfcc18,mfcc19,mfcc20
0,-0.286622,-1.618008,0.085470,0.342002,-0.499799,-0.776378,-1.749935,-0.187796,0.018807,-3.186727,...,0.886732,-0.921342,0.160322,-1.950076,-0.675093,2.095811,0.960045,3.101572,1.642159,0.383923
1,0.062018,-1.562914,0.305236,0.447540,-0.103498,-0.776378,-1.398961,-0.164109,-0.484784,-1.706009,...,1.153778,-2.071925,1.134710,-1.965194,-1.756498,1.144817,1.689571,1.779054,1.469588,0.271988
2,1.092476,-1.427839,-0.908544,-0.294322,-1.023783,-0.776378,-1.480883,0.790129,0.918671,-1.938466,...,1.670612,-0.348982,1.589764,-0.882939,-0.652456,1.582481,0.270070,1.863956,0.922576,0.056933
3,0.330889,-0.377849,-1.422418,-0.629180,-1.463543,-0.776378,-0.553826,1.121805,1.547780,-0.421892,...,-0.655488,-0.888152,0.342974,0.200433,-0.079387,1.067518,0.217717,0.272105,1.806972,0.687681
4,0.053858,-0.273925,-1.822824,-1.380979,-1.781383,-0.776378,-0.635632,1.887964,1.170838,-0.691961,...,0.653887,-0.681623,0.759681,-0.217852,0.150554,0.468052,0.305002,-0.229697,1.241727,0.115812

In [52]:
scaled_dataset['filename'] = data['filename']
scaled_dataset['genre'] = data['genre']

In [53]:
scaled_dataset.head()

,chroma_stft,rmse,spectral_centroid,spectral_bandwidth,rolloff,zero_crossing_rate,mfcc1,mfcc2,mfcc3,mfcc4,...,mfcc13,mfcc14,mfcc15,mfcc16,mfcc17,mfcc18,mfcc19,mfcc20,filename,genre
0,-0.286622,-1.618008,0.085470,0.342002,-0.499799,-0.776378,-1.749935,-0.187796,0.018807,-3.186727,...,0.160322,-1.950076,-0.675093,2.095811,0.960045,3.101572,1.642159,0.383923,prog01._The_Same_River.mp3chunk1,prog
1,0.062018,-1.562914,0.305236,0.447540,-0.103498,-0.776378,-1.398961,-0.164109,-0.484784,-1.706009,...,1.134710,-1.965194,-1.756498,1.144817,1.689571,1.779054,1.469588,0.271988,prog01._The_Same_River.mp3chunk2,prog
2,1.092476,-1.427839,-0.908544,-0.294322,-1.023783,-0.776378,-1.480883,0.790129,0.918671,-1.938466,...,1.589764,-0.882939,-0.652456,1.582481,0.270070,1.863956,0.922576,0.056933,prog01._The_Same_River.mp3chunk3,prog
3,0.330889,-0.377849,-1.422418,-0.629180,-1.463543,-0.776378,-0.553826,1.121805,1.547780,-0.421892,...,0.342974,0.200433,-0.079387,1.067518,0.217717,0.272105,1.806972,0.687681,prog01._The_Same_River.mp3chunk4,prog
4,0.053858,-0.273925,-1.822824,-1.380979,-1.781383,-0.776378,-0.635632,1.887964,1.170838,-0.691961,...,0.759681,-0.217852,0.150554,0.468052,0.305002,-0.229697,1.241727,0.115812,prog01._The_Same_River.mp3chunk5,prog

In [54]:
from sklearn.linear_model import LogisticRegression

In [55]:
model = LogisticRegression()

In [56]:
def extract_song_name(filename):
    parts = filename.split('._')
    song_name_with_extension = parts[1].split('.')[0] if len(parts) > 1 else 'Unknown'
    return song_name_with_extension.rsplit('.', 1)[0]

In [57]:
df = pd.DataFrame(scaled_dataset)

In [58]:
df['Song'] = df['filename'].apply(extract_song_name)

In [59]:
# //print all unique songs
df['Song'].unique()

array(['The_Same_River', 'In_the_Flesh',
       'Anekdoten_-_Our_Days_Are_Numbered', 'Unknown',
       'The_Road_Of_Bones', 'Part_V', 'Hallogallo', 'Folklore',
       'Bo_Hansson_-_Rohans_Horn_-_Slaget_vid_Pelennors_slatter',
       'Second_Life_Syndrome', 'Omen', 'Guardian',
       'When_the_Water_Breaks', 'Milliontown', 'Hazard_Profile_Part_One',
       'The_Solid_Time_of_Change_II', 'Vert', 'The_Light', 'Bleed_(live)',
       'The_Czar_I', 'Mister_Broken_Wings',
       'Violin_Concerto_in_E_minor_op', 'B',
       'Air_Supply_-_All_Out_Of_Love', 'In_A_Gadda_Da_Vida',
       'Planet_Earth', 'Frank_Sinatra_-_The_Girl_From_Ipanema',
       'Painkiller', 'Billy_Ray_Cyrus)',
       'My_Beautiful_Dark_Twisted_Fantasy_-_POWER', 'Rag_Doll',
       'Michael_Sembello_-_Maniac', 'Ascension_(feat', '(Feat',
       'This_Time', '2_-_1', 'Top_Of_The_World',
       'The_Cars_-_Bye_Bye_Love', 'Chip_Tha_Ripper)', 'Black_Hole_Sun',
       'The_Weeknd,_Swae_Lee', 'Ed_Sheeran_&_Future)', 'Ten-Day_Interval',
       'Blue_Jeans', 'Nice_Guy', 'Happier_Than_Ever', 'Tel_Aviv', '1)',
       'Goode'], dtype=object)

In [60]:
from sklearn.model_selection import GroupShuffleSplit

gss = GroupShuffleSplit(n_splits=1, test_size=0.1, random_state=42)
train_idx, test_idx = next(gss.split(df, groups=df['Song']))

# Create train and test DataFrames
train_df = df.iloc[train_idx]
test_df = df.iloc[test_idx]

# Print results
print("Train DataFrame:")
print(train_df)
print("\nTest DataFrame:")
print(test_df)

Train DataFrame:
       chroma_stft      rmse  spectral_centroid  spectral_bandwidth   rolloff  \
0        -0.286622 -1.618008           0.085470            0.342002 -0.499799
1         0.062018 -1.562914           0.305236            0.447540 -0.103498
2         1.092476 -1.427839          -0.908544           -0.294322 -1.023783
3         0.330889 -0.377849          -1.422418           -0.629180 -1.463543
4         0.053858 -0.273925          -1.822824           -1.380979 -1.781383
...            ...       ...                ...                 ...       ...
18741    -0.158719  0.327280           0.128613            0.334004 -0.109102
18742    -0.509275  0.364883           0.636616            0.695069  0.641172
18743    -0.525829  0.414520           0.616354            0.696166  0.556873
18744    -0.904077  0.650428           0.150822            0.301080 -0.018584
18745    -0.055842 -0.815028           0.763740            0.994996  0.788840

       zero_crossing_rate     mfcc1     mfcc2     mfcc3     mfcc4  ...  \
0               -0.776378 -1.749935 -0.187796  0.018807 -3.186727  ...
1               -0.776378 -1.398961 -0.164109 -0.484784 -1.706009  ...
2               -0.776378 -1.480883  0.790129  0.918671 -1.938466  ...
3               -0.776378 -0.553826  1.121805  1.547780 -0.421892  ...
4               -0.776378 -0.635632  1.887964  1.170838 -0.691961  ...
...                   ...       ...       ...       ...       ...  ...
18741            2.130734  0.727889  0.169385 -0.477717 -0.932272  ...
18742            2.130734  0.759418 -0.468480 -0.260411 -0.308026  ...
18743            2.130734  0.765974 -0.420390 -0.280541 -0.542530  ...
18744            2.130734  0.750779 -0.038414 -0.453093 -1.032549  ...
18745            2.130734 -0.658676 -0.860724  0.600865 -1.286017  ...

         mfcc14    mfcc15    mfcc16    mfcc17    mfcc18    mfcc19    mfcc20  \
0     -1.950076 -0.675093  2.095811  0.960045  3.101572  1.642159  0.383923
1     -1.965194 -1.756498  1.144817  1.689571  1.779054  1.469588  0.271988
2     -0.882939 -0.652456  1.582481  0.270070  1.863956  0.922576  0.056933
3      0.200433 -0.079387  1.067518  0.217717  0.272105  1.806972  0.687681
4     -0.217852  0.150554  0.468052  0.305002 -0.229697  1.241727  0.115812
...         ...       ...       ...       ...       ...       ...       ...
18741  0.767632 -0.396422  0.815343  0.100853  1.143329  0.133445  1.485702
18742  0.646584 -0.710463  1.324018 -0.393324 -0.292403 -0.139497  0.419064
18743  1.023694 -0.598059  1.108673 -0.533682 -0.124522 -0.058837  0.389844
18744  1.622999  0.349683  0.759815 -0.468527 -0.133839  0.060705  0.412368
18745  0.936332 -0.248011  0.454467 -0.068952  0.480826 -0.197330  0.730411

                                   filename     genre            Song
0          prog01._The_Same_River.mp3chunk1      prog  The_Same_River
1          prog01._The_Same_River.mp3chunk2      prog  The_Same_River
2          prog01._The_Same_River.mp3chunk3      prog  The_Same_River
3          prog01._The_Same_River.mp3chunk4      prog  The_Same_River
4          prog01._The_Same_River.mp3chunk5      prog  The_Same_River
...                                     ...       ...             ...
18741  nonprog07_Johnny_B._Goode.mp3chunk12  non_prog           Goode
18742  nonprog07_Johnny_B._Goode.mp3chunk13  non_prog           Goode
18743  nonprog07_Johnny_B._Goode.mp3chunk14  non_prog           Goode
18744  nonprog07_Johnny_B._Goode.mp3chunk15  non_prog           Goode
18745  nonprog07_Johnny_B._Goode.mp3chunk16  non_prog           Goode

[1965 rows x 29 columns]

Test DataFrame:
       chroma_stft      rmse  spectral_centroid  spectral_bandwidth   rolloff  \
174      -1.534557 -1.405490          -1.392303           -1.534758 -1.487693
175      -1.496925 -1.403534          -1.390854           -1.538270 -1.485924
176      -1.857528 -1.431345          -1.471216           -1.501394 -1.519992
177      -0.822737 -1.167199          -1.577002           -1.607228 -1.554209
178      -0.752264 -1.141040          -1.555127           -1.520761 -1.575016
...            ...       ...                ...                 ...       ...
19600     1.535647 -0.110191           1.296453            1.217391  1.530622
19601     1.142626  0.080297           1.500796            1.195728  1.576968
19602     1.560009  0.124855           1.492033            1.090082  1.487372
19603     1.356278  0.051869           1.176326            0.777677  1.146267
19604     2.226157 -0.547396          -0.519776            0.406176 -0.160144

       zero_crossing_rate     mfcc1     mfcc2     mfcc3     mfcc4  ...  \
174             -0.544673 -1.573439  0.735188  0.710642 -2.660719  ...
175             -0.544673 -1.460292  1.271527  0.603359 -2.631722  ...
176             -0.544673 -1.665790  1.409019  0.537345 -2.270476  ...
177             -0.544673 -1.159498  1.812721  0.482349 -1.870101  ...
178             -0.544673 -1.121601  1.815082  0.634236 -1.974771  ...
...                   ...       ...       ...       ...       ...  ...
19600            0.556312  0.526955 -0.962165 -0.226000  1.262120  ...
19601            0.556312  0.759706 -1.007968 -0.636482  1.312545  ...
19602            0.556312  0.810443 -1.019270 -0.704840  1.452837  ...
19603            0.556312  0.675565 -0.881866 -0.681228  1.692391  ...
19604            0.556312 -0.769076 -0.860017  1.979349  1.056549  ...

         mfcc14    mfcc15    mfcc16    mfcc17    mfcc18    mfcc19    mfcc20  \
174   -0.762170 -1.044123 -1.647684 -0.036577  1.604258  2.395219  2.710595
175   -1.226724 -1.136457 -0.869033  0.246498  0.553748  0.818245  1.085925
176   -1.369571 -1.498104 -1.072186  0.506925  0.052829  0.346129  0.537907
177   -1.487867 -0.711971 -1.200277 -0.055022  0.202789  0.314105 -0.181720
178   -1.433168 -0.357399 -0.858524 -0.463272 -0.654568 -0.325553 -0.353388
...         ...       ...       ...       ...       ...       ...       ...
19600  0.096379  0.464166 -0.442927  1.204498 -0.968635  2.261563 -1.818282
19601  0.303402  0.548422 -0.046948  1.440025 -1.336964  2.247471 -1.291483
19602  0.029712  0.347920 -0.389182  1.233379 -1.026399  2.130979 -1.496161
19603 -0.354271  0.136650 -0.732802  0.569400 -1.076291  1.940702 -1.315182
19604 -0.203521  0.109310 -0.976462 -0.269073 -1.206261  0.678996 -1.324629

                                          filename     genre     Song
174             prog07_-_Fool's_Overture.mp3chunk1      prog  Unknown
175             prog07_-_Fool's_Overture.mp3chunk2      prog  Unknown
176             prog07_-_Fool's_Overture.mp3chunk3      prog  Unknown
177             prog07_-_Fool's_Overture.mp3chunk4      prog  Unknown
178             prog07_-_Fool's_Overture.mp3chunk5      prog  Unknown
...                                            ...       ...      ...
19600  nonprogCranberries_-_04_-_Zombie.mp3chunk26  non_prog  Unknown
19601  nonprogCranberries_-_04_-_Zombie.mp3chunk27  non_prog  Unknown
19602  nonprogCranberries_-_04_-_Zombie.mp3chunk28  non_prog  Unknown
19603  nonprogCranberries_-_04_-_Zombie.mp3chunk29  non_prog  Unknown
19604  nonprogCranberries_-_04_-_Zombie.mp3chunk30  non_prog  Unknown

[17640 rows x 29 columns]

In [61]:
train_df.dtypes

chroma_stft           float64
rmse                  float64
spectral_centroid     float64
spectral_bandwidth    float64
rolloff               float64
zero_crossing_rate    float64
mfcc1                 float64
mfcc2                 float64
mfcc3                 float64
mfcc4                 float64
mfcc5                 float64
mfcc6                 float64
mfcc7                 float64
mfcc8                 float64
mfcc9                 float64
mfcc10                float64
mfcc11                float64
mfcc12                float64
mfcc13                float64
mfcc14                float64
mfcc15                float64
mfcc16                float64
mfcc17                float64
mfcc18                float64
mfcc19                float64
mfcc20                float64
filename               object
genre                  object
Song                   object
dtype: object

In [62]:
model.fit(train_df.drop(columns = ['genre', 'filename', 'Song']), train_df['genre'])

LogisticRegression()

In [63]:
train_df['pred'] = model.predict(train_df.drop(columns = ['genre', 'filename', 'Song']))
test_df['pred'] = model.predict(test_df.drop(columns = ['genre', 'filename', 'Song']))

/var/folders/m0/0p062cxn2rvbyqh1m3h8cb4c0000gn/T/ipykernel_16223/230968207.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df['pred'] = model.predict(train_df.drop(columns = ['genre', 'filename', 'Song']))
/var/folders/m0/0p062cxn2rvbyqh1m3h8cb4c0000gn/T/ipykernel_16223/230968207.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_df['pred'] = model.predict(test_df.drop(columns = ['genre', 'filename', 'Song']))

In [64]:
from sklearn.metrics import accuracy_score
accuracy_train = accuracy_score(train_df['genre'], train_df['pred'])
accuracy_test = accuracy_score(test_df['genre'], test_df['pred'])
print(accuracy_train)
print(accuracy_test)

0.8941475826972011
0.764795918367347

In [65]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
train_df['genre'] = label_encoder.fit_transform(train_df['genre'])
test_df['genre'] = label_encoder.transform(test_df['genre'])

/var/folders/m0/0p062cxn2rvbyqh1m3h8cb4c0000gn/T/ipykernel_16223/607645348.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df['genre'] = label_encoder.fit_transform(train_df['genre'])
/var/folders/m0/0p062cxn2rvbyqh1m3h8cb4c0000gn/T/ipykernel_16223/607645348.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_df['genre'] = label_encoder.transform(test_df['genre'])

In [66]:
X_train = train_df.drop(columns=['genre', 'filename', 'Song', 'pred'])
y_train = train_df['genre']
X_test = test_df.drop(columns=['genre', 'filename', 'Song', 'pred'])
y_test = test_df['genre']

In [67]:
import tensorflow as tf
from tensorflow.keras import regularizers
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping

model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(128, activation='relu', input_shape=(X_train.shape[1],)),  # Correct input shape
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(16, activation='relu'),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(8, activation='relu'),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

model.summary()

/Users/harlow/.local/share/virtualenvs/Progect-tV540T77/lib/python3.11/site-packages/keras/src/layers/core/dense.py:88: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 128)            │         3,456 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_5 (Dropout)             │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_6 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_7 (Dropout)             │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_8 (Dropout)             │ (None, 16)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_9 (Dropout)             │ (None, 8)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 14,465 (56.50 KB)

 Trainable params: 14,465 (56.50 KB)

 Non-trainable params: 0 (0.00 B)

In [68]:
history = model.fit(X_train, y_train, epochs=1000, verbose=1)
print("done")

Epoch 1/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 1s 653us/step - accuracy: 0.4948 - loss: 0.7709
Epoch 2/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 630us/step - accuracy: 0.5279 - loss: 0.7157
Epoch 3/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 559us/step - accuracy: 0.5921 - loss: 0.6876
Epoch 4/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 547us/step - accuracy: 0.6202 - loss: 0.6651
Epoch 5/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 571us/step - accuracy: 0.6069 - loss: 0.6750
Epoch 6/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 766us/step - accuracy: 0.6251 - loss: 0.6607
Epoch 7/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6291 - loss: 0.6573
Epoch 8/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 958us/step - accuracy: 0.6471 - loss: 0.6472
Epoch 9/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6251 - loss: 0.6491
Epoch 10/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6408 - loss: 0.6300
Epoch 11/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6684 - loss: 0.5996
Epoch 12/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6467 - loss: 0.5972
Epoch 13/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 706us/step - accuracy: 0.7283 - loss: 0.5183
Epoch 14/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 823us/step - accuracy: 0.7437 - loss: 0.4985
Epoch 15/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 679us/step - accuracy: 0.7558 - loss: 0.4584
Epoch 16/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 708us/step - accuracy: 0.7839 - loss: 0.4373
Epoch 17/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 660us/step - accuracy: 0.8227 - loss: 0.4189
Epoch 18/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 673us/step - accuracy: 0.8105 - loss: 0.3785
Epoch 19/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8231 - loss: 0.3849
Epoch 20/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 709us/step - accuracy: 0.8437 - loss: 0.3484
Epoch 21/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 652us/step - accuracy: 0.8487 - loss: 0.3522
Epoch 22/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 635us/step - accuracy: 0.8666 - loss: 0.3210
Epoch 23/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 659us/step - accuracy: 0.8629 - loss: 0.2971
Epoch 24/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 632us/step - accuracy: 0.8780 - loss: 0.3004
Epoch 25/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 814us/step - accuracy: 0.8715 - loss: 0.3153
Epoch 26/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 705us/step - accuracy: 0.8826 - loss: 0.2677
Epoch 27/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - accuracy: 0.8768 - loss: 0.2935
Epoch 28/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 802us/step - accuracy: 0.8940 - loss: 0.2642
Epoch 29/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8969 - loss: 0.2559
Epoch 30/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 704us/step - accuracy: 0.9123 - loss: 0.2426
Epoch 31/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 633us/step - accuracy: 0.8956 - loss: 0.2308
Epoch 32/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 672us/step - accuracy: 0.9144 - loss: 0.2116
Epoch 33/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 646us/step - accuracy: 0.9149 - loss: 0.2178
Epoch 34/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 625us/step - accuracy: 0.9194 - loss: 0.1841
Epoch 35/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 690us/step - accuracy: 0.9050 - loss: 0.2423
Epoch 36/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 698us/step - accuracy: 0.9107 - loss: 0.2261
Epoch 37/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 662us/step - accuracy: 0.9099 - loss: 0.2407
Epoch 38/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 780us/step - accuracy: 0.9006 - loss: 0.2611
Epoch 39/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 644us/step - accuracy: 0.9105 - loss: 0.2022
Epoch 40/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 640us/step - accuracy: 0.9142 - loss: 0.2095
Epoch 41/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 670us/step - accuracy: 0.9250 - loss: 0.1775
Epoch 42/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 645us/step - accuracy: 0.9193 - loss: 0.2018
Epoch 43/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 596us/step - accuracy: 0.9258 - loss: 0.1879
Epoch 44/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 610us/step - accuracy: 0.9328 - loss: 0.1687
Epoch 45/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 618us/step - accuracy: 0.9293 - loss: 0.1745
Epoch 46/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 583us/step - accuracy: 0.9188 - loss: 0.1859
Epoch 47/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 689us/step - accuracy: 0.9269 - loss: 0.1818
Epoch 48/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 614us/step - accuracy: 0.9329 - loss: 0.2029
Epoch 49/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 600us/step - accuracy: 0.9415 - loss: 0.1726
Epoch 50/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 618us/step - accuracy: 0.9313 - loss: 0.1640
Epoch 51/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 584us/step - accuracy: 0.9296 - loss: 0.1629
Epoch 52/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 770us/step - accuracy: 0.9381 - loss: 0.1844
Epoch 53/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 650us/step - accuracy: 0.9434 - loss: 0.1674
Epoch 54/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 611us/step - accuracy: 0.9438 - loss: 0.1514
Epoch 55/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 655us/step - accuracy: 0.9440 - loss: 0.1438
Epoch 56/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9503 - loss: 0.1424
Epoch 57/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 766us/step - accuracy: 0.9451 - loss: 0.1446
Epoch 58/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 611us/step - accuracy: 0.9293 - loss: 0.1457
Epoch 59/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 623us/step - accuracy: 0.9371 - loss: 0.1416
Epoch 60/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 578us/step - accuracy: 0.9418 - loss: 0.1302
Epoch 61/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 687us/step - accuracy: 0.9481 - loss: 0.1415
Epoch 62/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 588us/step - accuracy: 0.9318 - loss: 0.1533
Epoch 63/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 589us/step - accuracy: 0.9405 - loss: 0.1676
Epoch 64/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 754us/step - accuracy: 0.9295 - loss: 0.1470
Epoch 65/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 770us/step - accuracy: 0.9544 - loss: 0.1300
Epoch 66/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 586us/step - accuracy: 0.9409 - loss: 0.1468
Epoch 67/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 710us/step - accuracy: 0.9396 - loss: 0.1542
Epoch 68/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 681us/step - accuracy: 0.9350 - loss: 0.1469
Epoch 69/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 663us/step - accuracy: 0.9565 - loss: 0.1353
Epoch 70/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 626us/step - accuracy: 0.9309 - loss: 0.1785
Epoch 71/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 657us/step - accuracy: 0.9443 - loss: 0.1496
Epoch 72/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 611us/step - accuracy: 0.9469 - loss: 0.1324
Epoch 73/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 630us/step - accuracy: 0.9479 - loss: 0.1263
Epoch 74/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 646us/step - accuracy: 0.9410 - loss: 0.1396
Epoch 75/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 590us/step - accuracy: 0.9435 - loss: 0.1285
Epoch 76/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 573us/step - accuracy: 0.9551 - loss: 0.1073
Epoch 77/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 621us/step - accuracy: 0.9477 - loss: 0.1193
Epoch 78/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.9687 - loss: 0.0949
Epoch 79/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 628us/step - accuracy: 0.9567 - loss: 0.1168
Epoch 80/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 651us/step - accuracy: 0.9540 - loss: 0.1174
Epoch 81/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 610us/step - accuracy: 0.9451 - loss: 0.1151
Epoch 82/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 612us/step - accuracy: 0.9574 - loss: 0.1044
Epoch 83/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 663us/step - accuracy: 0.9456 - loss: 0.1138
Epoch 84/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 712us/step - accuracy: 0.9569 - loss: 0.1059
Epoch 85/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 642us/step - accuracy: 0.9521 - loss: 0.1436
Epoch 86/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 782us/step - accuracy: 0.9528 - loss: 0.1133
Epoch 87/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 648us/step - accuracy: 0.9441 - loss: 0.1114
Epoch 88/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 678us/step - accuracy: 0.9569 - loss: 0.1106
Epoch 89/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 603us/step - accuracy: 0.9476 - loss: 0.1131
Epoch 90/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 672us/step - accuracy: 0.9457 - loss: 0.1219
Epoch 91/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 668us/step - accuracy: 0.9523 - loss: 0.1166
Epoch 92/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 802us/step - accuracy: 0.9432 - loss: 0.1126
Epoch 93/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 582us/step - accuracy: 0.9532 - loss: 0.1080
Epoch 94/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 638us/step - accuracy: 0.9517 - loss: 0.1061
Epoch 95/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 727us/step - accuracy: 0.9532 - loss: 0.1080
Epoch 96/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 709us/step - accuracy: 0.9500 - loss: 0.1067
Epoch 97/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 760us/step - accuracy: 0.9617 - loss: 0.0919
Epoch 98/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 659us/step - accuracy: 0.9564 - loss: 0.1083
Epoch 99/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 716us/step - accuracy: 0.9590 - loss: 0.0970
Epoch 100/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 587us/step - accuracy: 0.9502 - loss: 0.1330
Epoch 101/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 661us/step - accuracy: 0.9623 - loss: 0.0901
Epoch 102/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 587us/step - accuracy: 0.9560 - loss: 0.0937
Epoch 103/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 578us/step - accuracy: 0.9590 - loss: 0.0923
Epoch 104/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 646us/step - accuracy: 0.9579 - loss: 0.0935
Epoch 105/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9511 - loss: 0.1127
Epoch 106/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 788us/step - accuracy: 0.9469 - loss: 0.1079
Epoch 107/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 689us/step - accuracy: 0.9585 - loss: 0.1313
Epoch 108/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 677us/step - accuracy: 0.9566 - loss: 0.1474
Epoch 109/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 574us/step - accuracy: 0.9603 - loss: 0.1027
Epoch 110/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 604us/step - accuracy: 0.9601 - loss: 0.0888
Epoch 111/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 578us/step - accuracy: 0.9499 - loss: 0.1039
Epoch 112/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 636us/step - accuracy: 0.9631 - loss: 0.0984
Epoch 113/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 637us/step - accuracy: 0.9596 - loss: 0.1039
Epoch 114/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 618us/step - accuracy: 0.9630 - loss: 0.0928
Epoch 115/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 598us/step - accuracy: 0.9537 - loss: 0.1021
Epoch 116/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step - accuracy: 0.9676 - loss: 0.0800
Epoch 117/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 611us/step - accuracy: 0.9676 - loss: 0.0862
Epoch 118/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 678us/step - accuracy: 0.9651 - loss: 0.0857
Epoch 119/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 613us/step - accuracy: 0.9688 - loss: 0.0815
Epoch 120/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 632us/step - accuracy: 0.9641 - loss: 0.0798
Epoch 121/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 740us/step - accuracy: 0.9597 - loss: 0.0814
Epoch 122/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 656us/step - accuracy: 0.9612 - loss: 0.0961
Epoch 123/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 621us/step - accuracy: 0.9628 - loss: 0.0806
Epoch 124/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 636us/step - accuracy: 0.9597 - loss: 0.1049
Epoch 125/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 655us/step - accuracy: 0.9648 - loss: 0.0883
Epoch 126/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 576us/step - accuracy: 0.9568 - loss: 0.0942
Epoch 127/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 571us/step - accuracy: 0.9597 - loss: 0.0986
Epoch 128/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 675us/step - accuracy: 0.9550 - loss: 0.0824
Epoch 129/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 645us/step - accuracy: 0.9565 - loss: 0.1022
Epoch 130/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 624us/step - accuracy: 0.9666 - loss: 0.0730
Epoch 131/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 572us/step - accuracy: 0.9711 - loss: 0.0731
Epoch 132/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 620us/step - accuracy: 0.9620 - loss: 0.1063
Epoch 133/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 638us/step - accuracy: 0.9616 - loss: 0.0950
Epoch 134/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 722us/step - accuracy: 0.9672 - loss: 0.0803
Epoch 135/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 618us/step - accuracy: 0.9636 - loss: 0.0969
Epoch 136/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 771us/step - accuracy: 0.9681 - loss: 0.0898
Epoch 137/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 587us/step - accuracy: 0.9673 - loss: 0.0805
Epoch 138/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 690us/step - accuracy: 0.9733 - loss: 0.0762
Epoch 139/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 665us/step - accuracy: 0.9667 - loss: 0.1090
Epoch 140/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 636us/step - accuracy: 0.9572 - loss: 0.0916
Epoch 141/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 627us/step - accuracy: 0.9617 - loss: 0.0840
Epoch 142/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 626us/step - accuracy: 0.9607 - loss: 0.0875
Epoch 143/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 660us/step - accuracy: 0.9606 - loss: 0.0772
Epoch 144/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 653us/step - accuracy: 0.9725 - loss: 0.0690
Epoch 145/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9641 - loss: 0.0692
Epoch 146/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 716us/step - accuracy: 0.9595 - loss: 0.0896
Epoch 147/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 612us/step - accuracy: 0.9660 - loss: 0.0983
Epoch 148/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 597us/step - accuracy: 0.9637 - loss: 0.0926
Epoch 149/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 821us/step - accuracy: 0.9564 - loss: 0.0986
Epoch 150/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 701us/step - accuracy: 0.9673 - loss: 0.0967
Epoch 151/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 664us/step - accuracy: 0.9529 - loss: 0.0912
Epoch 152/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 658us/step - accuracy: 0.9565 - loss: 0.1113
Epoch 153/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 667us/step - accuracy: 0.9708 - loss: 0.0835
Epoch 154/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 581us/step - accuracy: 0.9493 - loss: 0.0911
Epoch 155/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9564 - loss: 0.0887
Epoch 156/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 701us/step - accuracy: 0.9610 - loss: 0.0905
Epoch 157/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 646us/step - accuracy: 0.9712 - loss: 0.0750
Epoch 158/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 675us/step - accuracy: 0.9645 - loss: 0.0795
Epoch 159/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 726us/step - accuracy: 0.9628 - loss: 0.0952
Epoch 160/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 649us/step - accuracy: 0.9677 - loss: 0.0777
Epoch 161/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 676us/step - accuracy: 0.9677 - loss: 0.0801
Epoch 162/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 947us/step - accuracy: 0.9705 - loss: 0.0792
Epoch 163/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 674us/step - accuracy: 0.9623 - loss: 0.0812
Epoch 164/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 689us/step - accuracy: 0.9600 - loss: 0.1068
Epoch 165/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 639us/step - accuracy: 0.9686 - loss: 0.0730
Epoch 166/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 695us/step - accuracy: 0.9699 - loss: 0.0794
Epoch 167/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 618us/step - accuracy: 0.9595 - loss: 0.0712
Epoch 168/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 633us/step - accuracy: 0.9552 - loss: 0.1150
Epoch 169/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 709us/step - accuracy: 0.9567 - loss: 0.0852
Epoch 170/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 744us/step - accuracy: 0.9602 - loss: 0.0908
Epoch 171/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 734us/step - accuracy: 0.9616 - loss: 0.0865
Epoch 172/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 750us/step - accuracy: 0.9677 - loss: 0.0793
Epoch 173/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 697us/step - accuracy: 0.9673 - loss: 0.0792
Epoch 174/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 757us/step - accuracy: 0.9680 - loss: 0.0883
Epoch 175/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 669us/step - accuracy: 0.9763 - loss: 0.0703
Epoch 176/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 812us/step - accuracy: 0.9574 - loss: 0.0887
Epoch 177/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 592us/step - accuracy: 0.9686 - loss: 0.0682
Epoch 178/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 646us/step - accuracy: 0.9662 - loss: 0.0687
Epoch 179/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 629us/step - accuracy: 0.9645 - loss: 0.0746
Epoch 180/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9677 - loss: 0.0778
Epoch 181/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 666us/step - accuracy: 0.9688 - loss: 0.0793
Epoch 182/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 722us/step - accuracy: 0.9595 - loss: 0.0818
Epoch 183/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 629us/step - accuracy: 0.9719 - loss: 0.0822
Epoch 184/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 683us/step - accuracy: 0.9662 - loss: 0.0759
Epoch 185/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 620us/step - accuracy: 0.9646 - loss: 0.0890
Epoch 186/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 649us/step - accuracy: 0.9620 - loss: 0.0767
Epoch 187/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 665us/step - accuracy: 0.9605 - loss: 0.0809
Epoch 188/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 674us/step - accuracy: 0.9552 - loss: 0.0852
Epoch 189/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 894us/step - accuracy: 0.9581 - loss: 0.0767
Epoch 190/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 678us/step - accuracy: 0.9507 - loss: 0.0927
Epoch 191/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 862us/step - accuracy: 0.9728 - loss: 0.0652
Epoch 192/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 669us/step - accuracy: 0.9673 - loss: 0.0677
Epoch 193/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 748us/step - accuracy: 0.9703 - loss: 0.0654
Epoch 194/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 656us/step - accuracy: 0.9713 - loss: 0.0592
Epoch 195/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 728us/step - accuracy: 0.9617 - loss: 0.0785
Epoch 196/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 784us/step - accuracy: 0.9680 - loss: 0.0724
Epoch 197/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 641us/step - accuracy: 0.9680 - loss: 0.0869
Epoch 198/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - accuracy: 0.9759 - loss: 0.0635
Epoch 199/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 795us/step - accuracy: 0.9631 - loss: 0.1496
Epoch 200/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 618us/step - accuracy: 0.9644 - loss: 0.0843
Epoch 201/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 667us/step - accuracy: 0.9720 - loss: 0.0777
Epoch 202/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 752us/step - accuracy: 0.9586 - loss: 0.0798
Epoch 203/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 856us/step - accuracy: 0.9629 - loss: 0.0820
Epoch 204/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 689us/step - accuracy: 0.9706 - loss: 0.0735
Epoch 205/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step - accuracy: 0.9721 - loss: 0.0660
Epoch 206/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 699us/step - accuracy: 0.9630 - loss: 0.0989
Epoch 207/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 666us/step - accuracy: 0.9627 - loss: 0.0870
Epoch 208/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 722us/step - accuracy: 0.9653 - loss: 0.0847
Epoch 209/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9667 - loss: 0.0777
Epoch 210/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 666us/step - accuracy: 0.9635 - loss: 0.0846
Epoch 211/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 690us/step - accuracy: 0.9651 - loss: 0.0817
Epoch 212/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 659us/step - accuracy: 0.9623 - loss: 0.0892
Epoch 213/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9668 - loss: 0.0721
Epoch 214/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 653us/step - accuracy: 0.9702 - loss: 0.0699
Epoch 215/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 856us/step - accuracy: 0.9676 - loss: 0.0866
Epoch 216/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 677us/step - accuracy: 0.9703 - loss: 0.0664
Epoch 217/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 672us/step - accuracy: 0.9638 - loss: 0.0736
Epoch 218/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 617us/step - accuracy: 0.9680 - loss: 0.0764
Epoch 219/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 641us/step - accuracy: 0.9635 - loss: 0.0770
Epoch 220/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 631us/step - accuracy: 0.9675 - loss: 0.0690
Epoch 221/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 644us/step - accuracy: 0.9716 - loss: 0.0723
Epoch 222/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 623us/step - accuracy: 0.9715 - loss: 0.0610
Epoch 223/1000
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 619us/step - accuracy: 0.9745 - loss: 0.0584
Epoch 224/1000

In [69]:
test_loss, test_acc = model.evaluate(X_test, y_test, verbose=2)
print(f"Test Accuracy: {test_acc*100:.2f}%")

552/552 - 0s - 421us/step - accuracy: 0.7598 - loss: 7.5597
Test Accuracy: 75.98%

In [70]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 128)            │         3,456 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_5 (Dropout)             │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_6 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_7 (Dropout)             │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_8 (Dropout)             │ (None, 16)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_9 (Dropout)             │ (None, 8)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 43,397 (169.52 KB)

 Trainable params: 14,465 (56.50 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 28,932 (113.02 KB)